package com.Testingonapplications;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
public class UI_Testing {
	public static final String URL = "https://www.getcalley.com/page-sitemap.xml";
	public static void main(String[] args) throws Exception {
		UI_Testing ut=new UI_Testing();
		ut.chromeresolution1();
		ut.Edgeresolution1();
		ut.Firefoxresolution1();
		ut.chromeresolution2();
		ut.Edgeresolution2();
		ut.Firefoxresolution2();
		ut.chromeresolution3();
		ut.Edgeresolution3();
		ut.Firefoxresolution3();
		ut.chromeresolution4();
		ut.Edgeresolution4();
		ut.Firefoxresolution4();
		ut.chromeresolution5();
		ut.Edgeresolution5();
		ut.Firefoxresolution5();
	}
	public void chromeresolution1() throws IOException, InterruptedException {
		 MutableCapabilities caps = new MutableCapabilities();
		 caps.setCapability("browserName", "chrome");
		 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
		 browserstackOptions.put("os", "Windows");
		 browserstackOptions.put("osVersion", "10");
		 browserstackOptions.put("resolution", "1920×1080");
		 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
		 browserstackOptions.put("sessionName", "Screen Resolution test");
		 browserstackOptions.put("seleniumVersion", "4.5.0");
		caps.setCapability("bstack:options", browserstackOptions);
		ChromeOptions opt=new ChromeOptions();
		opt.addArguments("--remote-allow-origins=*");
		opt.addArguments("--disable-notifications");
		WebDriver driver=new ChromeDriver(opt);
		driver.get("https://www.getcalley.com/blog/");
		TakesScreenshot ss = (TakesScreenshot)driver;
		File src = ss.getScreenshotAs(OutputType.FILE);
		File trg = new File("./screenshot1/getcalley1.png");
		FileUtils.copyFile(src, trg);
		Thread.sleep(2000);
		driver.quit();
	}
	public void Edgeresolution1() throws IOException, InterruptedException {
		 MutableCapabilities caps = new MutableCapabilities();
		 caps.setCapability("browserName", "safari");
		 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
		 browserstackOptions.put("os", "Windows");
		 browserstackOptions.put("osVersion", "10");
		 browserstackOptions.put("resolution", "1366×768");
		 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
		 browserstackOptions.put("sessionName", "Screen Resolution test");
		 browserstackOptions.put("seleniumVersion", "4.5.0");
		caps.setCapability("bstack:options", browserstackOptions);
		EdgeOptions opt=new EdgeOptions();
		opt.addArguments("--disable-notifications");
		WebDriver driver=new EdgeDriver(opt);
		driver.get("https://www.getcalley.com/blog/");
		TakesScreenshot ss = (TakesScreenshot)driver;
		File src = ss.getScreenshotAs(OutputType.FILE);
		File trg = new File("./screenshot1/getcalley2.png");
		FileUtils.copyFile(src, trg);
		Thread.sleep(2000);
		driver.quit();
	}
	public void Firefoxresolution1() throws IOException, InterruptedException {
		MutableCapabilities caps = new MutableCapabilities();
		 caps.setCapability("browserName", "Firefox");
		 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
		 browserstackOptions.put("os", "Windows");
		 browserstackOptions.put("osVersion", "10");
		 browserstackOptions.put("resolution", "1536×864 ");
		 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
		 browserstackOptions.put("sessionName", "Screen Resolution test");
		 browserstackOptions.put("seleniumVersion", "4.5.0");
		caps.setCapability("bstack:options", browserstackOptions);
		FirefoxOptions opt=new FirefoxOptions();
	    opt.addArguments("--disable-notifications");
		FirefoxDriver driver=new FirefoxDriver();
		driver.get("https://www.getcalley.com/blog/");
		TakesScreenshot ss = (TakesScreenshot)driver;
		File src = ss.getScreenshotAs(OutputType.FILE);
		File trg = new File("./screenshot1/getcalley3.png");
		FileUtils.copyFile(src, trg);
		Thread.sleep(2000);
		driver.quit();
	}
public void chromeresolution2() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "chrome");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1920×1080");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	ChromeOptions opt=new ChromeOptions();
	opt.addArguments("--remote-allow-origins=*");
	opt.addArguments("--disable-notifications");
	WebDriver driver=new ChromeDriver(opt);
	driver.get("https://www.getcalley.com/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley4.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Edgeresolution2() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "Edge");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1366×768");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	EdgeOptions opt=new EdgeOptions();
	opt.addArguments("--disable-notifications");
	WebDriver driver=new EdgeDriver(opt);
	driver.get("https://www.getcalley.com/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley5.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Firefoxresolution2() throws IOException, InterruptedException {
	MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "Firefox");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1536×864 ");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	FirefoxOptions opt=new FirefoxOptions();
   opt.addArguments("--disable-notifications");
	WebDriver driver=new FirefoxDriver(opt);
	driver.get("https://www.getcalley.com/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley6.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void chromeresolution3() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "chrome");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1920×1080");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	ChromeOptions opt=new ChromeOptions();
	opt.addArguments("--remote-allow-origins=*");
	opt.addArguments("--disable-notifications");
	WebDriver driver=new ChromeDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-teams-plan-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley7.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Edgeresolution3() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "safari");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1366×768");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	EdgeOptions opt=new EdgeOptions();
	opt.addArguments("--disable-notifications");
	WebDriver driver=new EdgeDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-teams-plan-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley8.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Firefoxresolution3() throws IOException, InterruptedException {
	MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "Firefox");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1536×864 ");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	FirefoxOptions opt=new FirefoxOptions();
   opt.addArguments("--disable-notifications");
	WebDriver driver=new FirefoxDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-teams-plan-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley9.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void chromeresolution4() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "chrome");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1920×1080");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	ChromeOptions opt=new ChromeOptions();
	opt.addArguments("--remote-allow-origins=*");
	opt.addArguments("--disable-notifications");
	WebDriver driver=new ChromeDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-pro-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley10.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Edgeresolution4() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "safari");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1366×768");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	EdgeOptions opt=new EdgeOptions();
	opt.addArguments("--disable-notifications");
	WebDriver driver=new EdgeDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-pro-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley11.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Firefoxresolution4() throws IOException, InterruptedException {
	MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "Firefox");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1536×864 ");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	FirefoxOptions opt=new FirefoxOptions();
    opt.addArguments("--disable-notifications");
	WebDriver driver=new FirefoxDriver(opt);
	driver.get("https://www.getcalley.com/free-trial-calley-pro-v2/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley12.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void chromeresolution5() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "chrome");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1920×1080");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	ChromeOptions opt=new ChromeOptions();
	opt.addArguments("--remote-allow-origins=*");
	opt.addArguments("--disable-notifications");
	WebDriver driver=new ChromeDriver(opt);
	driver.get("https://www.getcalley.com/why-automatic-call-dialer-software/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley13.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Edgeresolution5() throws IOException, InterruptedException {
	 MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "safari");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1366×768");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	EdgeOptions opt=new EdgeOptions();
	opt.addArguments("--disable-notifications");
	WebDriver driver=new EdgeDriver(opt);
	driver.get("https://www.getcalley.com/why-automatic-call-dialer-software/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley14.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
public void Firefoxresolution5() throws IOException, InterruptedException {
	MutableCapabilities caps = new MutableCapabilities();
	 caps.setCapability("browserName", "safari");
	 HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	 browserstackOptions.put("os", "Windows");
	 browserstackOptions.put("osVersion", "10");
	 browserstackOptions.put("resolution", "1536×864 ");
	 browserstackOptions.put("buildName", "Java Screen Resolution test Sample Build");
	 browserstackOptions.put("sessionName", "Screen Resolution test");
	 browserstackOptions.put("seleniumVersion", "4.5.0");
	caps.setCapability("bstack:options", browserstackOptions);
	FirefoxOptions opt=new FirefoxOptions();
    opt.addArguments("--disable-notifications");
	WebDriver driver=new FirefoxDriver(opt);
	driver.get("https://www.getcalley.com/why-automatic-call-dialer-software/");
	TakesScreenshot ss = (TakesScreenshot)driver;
	File src = ss.getScreenshotAs(OutputType.FILE);
	File trg = new File("./screenshot1/getcalley15.png");
	FileUtils.copyFile(src, trg);
	Thread.sleep(2000);
	driver.quit();
}
}
